#!/bin/bash

project=$(stack path | grep project-root: | awk '{print $2}')
cabal=$(ls $project/*.cabal)
executable=$(grep -e '^executable' $cabal | head -n 1 | awk '{print $2}')

stack build

if [ "$1" = "--" ]; then
    shift
fi
stack exec $executable -- $@
